#! /bin/sh

docker run \
	--env "NAME_SERVERS=192.168.8.43 192.168.8.33" \
	--env "X_PYTHON_NAME_SERVERS=192.168.8.43 192.168.8.33" \
	-v /opt/github/universal-web-redirect/python:/opt/python \
	-p 192.168.1.145:80:80 \
	-p 127.0.0.1:80:80 \
	-it universal-web-redirect $*
